import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  UserButton,
} from "@clerk/nextjs";
import Navbar from "./Components/Navbar";
import ToastProvider from "./Providers/page";
import Footer from "./Components/Footer";
import { Inter } from "next/font/google";
import { CartProvider } from "@/app/Context/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          <CartProvider>
            {children}
          </CartProvider>
          <ToastProvider />
          <Footer />
        </body>
      </html>
      <SignedOut>
        <SignInButton /> {/* Shows sign-in button when signed out */}
      </SignedOut>
    </ClerkProvider>
  );
}
